version: '3.1'

services:

  db:
    build: postgres/.
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=db1
    ports:
      - 5432:5432